/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifpb.view;

/**
 *
 * @author claudio
 */
public class JanelaSistema extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaSistema() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagemLogo = new javax.swing.JLabel();
        LogoIMC = new javax.swing.JLabel();
        ImagemCadastro = new javax.swing.JLabel();
        BotaoSair = new javax.swing.JButton();
        ImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 556));
        setMinimumSize(new java.awt.Dimension(850, 556));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fotos-logo-academiaOK.png"))); // NOI18N
        getContentPane().add(ImagemLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 390, 260));

        LogoIMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoIMC.png"))); // NOI18N
        LogoIMC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoIMCMouseClicked(evt);
            }
        });
        getContentPane().add(LogoIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 150, 160));

        ImagemCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadastreseOK.png"))); // NOI18N
        ImagemCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagemCadastroMouseClicked(evt);
            }
        });
        getContentPane().add(ImagemCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 310, 140));

        BotaoSair.setBackground(new java.awt.Color(255, 0, 0));
        BotaoSair.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BotaoSair.setForeground(new java.awt.Color(0, 0, 0));
        BotaoSair.setText("SAIR");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        ImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AcademiaAjustada.jpg"))); // NOI18N
        getContentPane().add(ImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed

        System.exit(0);
        
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void ImagemCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemCadastroMouseClicked

        dispose();
        new JanelaCadastrarPessoa().setVisible(true);
        
    }//GEN-LAST:event_ImagemCadastroMouseClicked

    private void LogoIMCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoIMCMouseClicked

        dispose();
        new JanelaCalculaImc().setVisible(true);
        
    }//GEN-LAST:event_LogoIMCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSair;
    private javax.swing.JLabel ImagemCadastro;
    private javax.swing.JLabel ImagemFundo;
    private javax.swing.JLabel ImagemLogo;
    private javax.swing.JLabel LogoIMC;
    // End of variables declaration//GEN-END:variables
}
